### PR TITLE
fix(gsd): seed preferences.md into auto-mode worktrees

### LINKED ISSUE #2684: [Bug]: preferences.md not copied to auto-mode worktree — post_unit_hooks silently disabled
## Summary

`preferences.md` is not seeded into auto-mode worktrees when they are created. Because post-unit hooks (and all other preference-driven config) are defined in `preferences.md`, any hook configured there silently stops firing once auto-mode enters a worktree.

## Root Cause

`copyPlanningArtifacts()` in `src/resources/extensions/gsd/auto-worktree.ts` explicitly lists the files to copy from the source repo's `.gsd/` into the fresh worktree. `preferences.md` is absent from that list:

```typescript
// auto-worktree.ts ~line 630
for (const file of [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "QUEUE.md",
  "STATE.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
]) {
  safeCopy(join(srcGsd, file), join(dstGsd, file), { force: true });
}
// ^^^ preferences.md is missing
```

The same gap exists in `ROOT_STATE_FILES` (~line 50), which drives `syncGsdStateToWorktree()` and `syncWorktreeStateBack()` — so even the ongoing sync passes don't propagate preferences:

```typescript
const ROOT_STATE_FILES = [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
  "QUEUE.md",
  "completed-units.json",
  "metrics.json",
] as const;
// ^^^ preferences.md is missing here too
```

Because `.gsd/` is blanket-gitignored by default, git worktrees are empty fresh checkouts — the worktree bootstrap is the only opportunity to carry config over. Without it, the worktree's `.gsd/` has no `preferences.md` at all.

## Impact

- All `post_unit_hooks` (Telegram, Slack, Discord notifications, custom scripts, etc.) stop firing silently as soon as auto-mode enters a worktree
- `always_use_skills`, `prefer_skills`, `avoid_skills`, and `skill_rules` are ignored inside worktrees
- `custom_instructions` are ignored inside worktrees
- `git.auto_push`, `git.main_branch`, and other git prefs fall back to defaults inside the worktree (the effective preferences loader does load a fallback, but the project-level overrides are lost)
- The bug is silent — no error, no warning, execution continues normally but hooks never fire

## Reproduction

1. Configure a `post_unit_hooks` entry in `.gsd/preferences.md` (e.g. a Telegram notification)
2. Ensure `git.isolation: worktree` is set (the default)
3. Run `/gsd auto`
4. Observe: hooks fire for any milestone that ran before auto-mode created a worktree, then stop completely once the first worktree is entered
5. Confirm: `.gsd/worktrees/<MID>/.gsd/preferences.md` does not exist

## Fix

Add `preferences.md` to both locations:

**1. `copyPlanningArtifacts()`** — the initial seed on worktree creation:

```typescript
for (const file of [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "QUEUE.md",
  "STATE.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
+ "preferences.md",
]) {
  safeCopy(join(srcGsd, file), join(dstGsd, file), { force: true });
}
```

**2. `ROOT_STATE_FILES`** — so ongoing sync passes also propagate it:

```typescript
const ROOT_STATE_FILES = [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
  "QUEUE.md",
  "completed-units.json",
  "metrics.json",
+ "preferences.md",
] as const;
```

Note: `preferences.md` should be copied with `force: false` in `syncGsdStateToWorktree()` (additive, project root → worktree) but `force: true` for the initial seed — same pattern as other planning files. The worktree should never override project-root preferences during execution, so the sync-back direction (`syncWorktreeStateBack`) should likely `force: false` for preferences to avoid overwriting changes made via `/gsd prefs` in the main session.

## Environment

- Reproduced on: Windows 11, gsd-gui project, M006/M007 hooks fired (ran before worktree mode), M008 hooks silent (ran inside worktree)
- `git.isolation: worktree` (default)
- Hook type: `post_unit_hooks` with `curl` Telegram notification

### PR DESCRIPTION
**Pull request by drkthng**
TL;DR

 What: Seed preferences.md into auto-mode worktrees on creation and forward-sync.
 Why: preferences.md was missing from both seed lists, so post_unit_hooks, skill rules, and custom instructions were silently unavailable in worktrees.
 How: Add preferences.md to copyPlanningArtifacts() and a dedicated forward-sync in syncGsdStateToWorktree(), deliberately kept out of ROOT_STATE_FILES to prevent back-sync overwrite.

 What

 Two locations in auto-worktree.ts maintain lists of .gsd/ files to copy into worktrees. preferences.md was absent from both:
 - copyPlanningArtifacts() — initial seed on worktree creation
 - syncGsdStateToWorktree() — ongoing forward-sync

 Why

 Any configuration in preferences.md — including post_unit_hooks, skill rules, and custom instructions — was silently unavailable inside auto-mode worktrees.

 Closes #2684

 How

 - Added "preferences.md" to the copyPlanningArtifacts() file list.
 - Added a dedicated forward-sync block in syncGsdStateToWorktree() with the same additive-only guard (!existsSync(dst)) used by ROOT_STATE_FILES.
 - Not added to ROOT_STATE_FILES because that constant also drives syncWorktreeStateBack(), which copies worktree → project root with force: true. The project root is authoritative for
 preferences — worktree copies must never overwrite it.

 Change type

 - fix — Bug fix
 - test — Adding or updating tests

 Scope

 - gsd extension — GSD workflow

 Breaking changes

 - No breaking changes

 Test plan

 - CI passes
 - New/updated tests included — 3 regression tests in worktree-preferences-sync.test.ts

 AI disclosure

 - This PR includes AI-assisted code — generated with GSD/Claude Code, all tests verified locally

### CODE REVIEW

**Comment by drkthng** [comment]
> ## 🔴 PR Risk Report — CRITICAL
> **Files changed**	2
> **Systems affected**	2
> **Overall risk**	🔴 CRITICAL
> ### Affected Systems
> Risk	System
> 🔴 critical	Auto Engine
> 🟡 medium	Worktree
> File Breakdown
> Risk	File	Systems
> 🔴	`src/resources/extensions/gsd/auto-worktree.ts`	Auto Engine, Worktree
> ⚪	`src/resources/extensions/gsd/tests/worktree-preferences-sync.test.ts`	_(unclassified)_
> > ⚠️ **Critical risk** — please verify: state persistence, auth token lifecycle, agent loop race conditions, RPC protocol compatibility.

The bot flags auto-worktree.ts as critical by default. This change adds preferences.md to two file-copy lists — no state machine, auth, or concurrency changes.

File: src/resources/extensions/gsd/auto-worktree.ts [hunk 1]
```diff
@@ -946,6 +962,7 @@ function copyPlanningArtifacts(srcBase: string, wtPath: string): void {
     "STATE.md",
     "KNOWLEDGE.md",
     "OVERRIDES.md",
+    "preferences.md",
```
Comment (igouss) [inline src/resources/extensions/gsd/auto-worktree.ts:965]: Should we keep it UPPSERCASE for consistency?

Comment (drkthng) [reply src/resources/extensions/gsd/auto-worktree.ts:965]: Good eye — the inconsistency is real. But preferences.md is the existing filename used across the codebase (loader, docs, detection logic). This PR just adds it to the copy lists. A rename to PREFERENCES.md would be a broader change and should be its own PR to keep this one focused on the bug fix.

Comment (drkthng) [reply src/resources/extensions/gsd/auto-worktree.ts:965]: Checked — 36 files reference preferences.md across source, tests, and docs. A rename would also need a migration path for existing users' files. Probably not worth the churn for cosmetic consistency, but happy to open an issue if the team feels strongly.

**Comment by igouss** [comment]
Personally I think consistency is important, and would affect any future users. Maybe we can do a migration path?

**Comment by drkthng** [comment]
> Personally I think consistency is important, and would affect any future users. Maybe we can do a migration path?

Agreed consistency matters. This is big enough to be its own PR though — 36 files plus a migration path (loader fallback for existing preferences.md → PREFERENCES.md). Want me to open an issue to track it? Happy to pick it up as a follow-up once this fix lands.

**Comment by igouss** [comment]
I'm just a contributor not a project owner - up to you ;-)

**Comment by jeremymcs** [comment]
> I'm just a contributor not a project owner - up to you ;-)

+1 on ALL CAPS

**Comment by drkthng** [comment]
> > I'm just a contributor not a project owner - up to you ;-)
> 
> +1 on ALL CAPS

put it into this issue https://github.com/gsd-build/gsd-2/issues/2700
but it got flagged, maybe it helps if you mention your support there
