### PR TITLE
fix: parse hook/ compound unit types correctly in missing-artifact detection

### LINKED ISSUE #2826: forensics + doctor: hook/* completed-unit keys parsed incorrectly — false-positive missing-artifact errors for all hook units
## Problem

`/gsd forensics` reports false-positive `missing-artifact` errors for every completed `hook/*` unit (e.g. `hook/telegram-progress/M007/S01`). The hook ran successfully and is correctly recorded in `completed-units.json`, but the forensics anomaly detector flags it as stale/missing, producing noise that makes the report unreliable.

## Root Cause

`detectMissingArtifacts` in `forensics.js` (and the same pattern in `doctor-runtime-checks.js`) uses `key.indexOf("/")` to split a completed-unit key into `unitType` and `unitId`. This works for single-segment types like `"execute-task"` but silently breaks for hook units whose type is a **compound slash-delimited string** (`"hook/<hookName>"`):

```
key = "hook/telegram-progress/M007/S01"
                    ↑
         indexOf("/") finds index 4

unitType = key.slice(0, 4)    → "hook"                      ❌ (should be "hook/telegram-progress")
unitId   = key.slice(5)       → "telegram-progress/M007/S01" ❌ (should be "M007/S01")
```

`verifyExpectedArtifact` then receives `("hook", "telegram-progress/M007/S01", base)`. Its guard on line 133 is:

```js
if (unitType.startsWith("hook/")) return true;
```

`"hook".startsWith("hook/")` is **false** — the guard is bypassed, artifact path resolution fails, and a false-positive `missing-artifact` anomaly is pushed.

### Affected files and lines

**`forensics.js` — `detectMissingArtifacts`** (~line 524):
```js
// BUGGY
const slashIdx = key.indexOf("/");
if (slashIdx === -1) continue;
const unitType = key.slice(0, slashIdx);  // → "hook" for hook units ❌
const unitId   = key.slice(slashIdx + 1);
```

**`doctor-runtime-checks.js` — orphaned-key check** (~line 114):
```js
// Same bug — identical pattern
const slashIdx = key.indexOf("/");
if (slashIdx === -1) continue;
const unitType = key.slice(0, slashIdx);  // → "hook" for hook units ❌
const unitId   = key.slice(slashIdx + 1);
```

Note: `detectStuckLoops` in the same `forensics.js` file (~line 472) already uses the **correct** idiom — `const [unitType, ...idParts] = key.split("/")` — but the two anomaly-detection functions above do not.

## Expected Behavior

Hook units with compound types (`hook/<hookName>`) should be correctly split so that `verifyExpectedArtifact` receives the full compound type (e.g. `"hook/telegram-progress"`) and immediately returns `true` via the existing `unitType.startsWith("hook/")` guard. No `missing-artifact` anomaly should be raised.

## Fix

Replace the `indexOf("/")` split in **both** locations with a hook-aware split:

```js
let unitType: string;
let unitId: string;
if (key.startsWith("hook/")) {
    // Hook unit types are two segments: "hook/<hookName>"
    const secondSlash = key.indexOf("/", 5); // skip past "hook/"
    if (secondSlash === -1) continue;        // malformed key
    unitType = key.slice(0, secondSlash);    // → "hook/telegram-progress" ✅
    unitId   = key.slice(secondSlash + 1);   // → "M007/S01" ✅
} else {
    const slashIdx = key.indexOf("/");
    if (slashIdx === -1) continue;
    unitType = key.slice(0, slashIdx);
    unitId   = key.slice(slashIdx + 1);
}
```

Alternatively, extract a shared `splitCompletedKey(key)` helper and use it in both `forensics.js` and `doctor-runtime-checks.js` to prevent future drift.

## Environment

- GSD version: 2.53.0
- Model: claude-sonnet-4-6
- Unit types affected: any `hook/*` unit (confirmed with `hook/telegram-progress`)

## Reproduction Context

Any project with `post_unit_hooks` configured in `preferences.md`. After hooks complete successfully, completed-units.json contains entries like `"hook/telegram-progress/M007/S01"`. Running `/gsd forensics` then produces one `[ERROR] missing-artifact` entry per hook key.

## Forensic Evidence

From `completed-units.json` (actual file contents):
```
"hook/telegram-progress/M007/S01"
"hook/telegram-progress/M007/S02/T01"
"hook/telegram-progress/M007/S02/T02"
"hook/telegram-progress/M007/S02"
"hook/telegram-progress/M007"
```

All 5 flagged as `missing-artifact` errors in the forensics report — one per hook entry.

The anomaly message for each:
> The unit is recorded as completed but verifyExpectedArtifact() returns false at both project root and worktree. The completion state is stale.

`verifyExpectedArtifact` is never at fault — it correctly returns `true` for `unitType.startsWith("hook/")`. The bug is entirely in how `unitType` is extracted before the call.

---
*Auto-generated by `/gsd forensics`*

### PR DESCRIPTION
**Pull request by drkthng**
## Problem

`detectMissingArtifacts()` in `forensics.ts` and the orphaned-key check in `doctor-runtime-checks.ts` both use `key.indexOf("/")` to split a completed-unit key into `unitType` and `unitId`. This works for single-segment types like `"execute-task"` but silently breaks for hook units whose type is a **compound slash-delimited string** (`"hook/<hookName>"`):

```
key      = "hook/telegram-progress/M007/S01"
                    ↑
         indexOf("/") finds index 4

unitType = key.slice(0, 4) → "hook"                       ❌
unitId   = key.slice(5)    → "telegram-progress/M007/S01" ❌
```

`verifyExpectedArtifact()` then receives `("hook", "telegram-progress/M007/S01", base)`. Its guard is:

```ts
if (unitType.startsWith("hook/")) return true;
```

`"hook".startsWith("hook/")` is **false** — the guard is bypassed, artifact path resolution fails, and a false-positive `missing-artifact` anomaly is emitted for every completed hook unit.

## Fix

Detect the `hook/` prefix and split on the **second** slash instead of the first. Both affected call sites are patched identically.

The same `forensics.ts` file already uses the correct idiom in `detectStuckLoops()` — `const [unitType, ...idParts] = key.split("/")` — but the two anomaly-detection functions did not.

## Testing

Verified by inspection against the live `completed-units.json` containing five `hook/telegram-progress/M007/*` entries that were incorrectly producing errors. After the fix, `unitType = "hook/telegram-progress"` which satisfies `startsWith("hook/")` and `verifyExpectedArtifact()` returns `true` immediately.

Closes #2826

### CODE REVIEW

File: src/resources/extensions/gsd/forensics.ts [hunk 1]
```diff
@@ -654,10 +654,22 @@ function detectMissingArtifacts(completedKeys: string[], basePath: string, activ
   const wtBasePath = activeMilestone ? getAutoWorktreePath(basePath, activeMilestone) : null;
 
   for (const key of completedKeys) {
-    const slashIdx = key.indexOf("/");
-    if (slashIdx === -1) continue;
-    const unitType = key.slice(0, slashIdx);
-    const unitId = key.slice(slashIdx + 1);
+    // Hook unit types are compound: "hook/<hookName>". Split on the *second*
```
Comment (igouss) [inline src/resources/extensions/gsd/forensics.ts]: exact dup of the code, above, maybe can be refactored into a helper?

Comment (drkthng) [reply src/resources/extensions/gsd/forensics.ts]: Good call — extracted splitCompletedKey() as an exported helper in forensics.ts and updated both call sites to use it. Tests updated too. Pushed in the latest commit.

**Comment by glittercowboy** [comment]
This PR now has merge conflicts after #2820 and #2898 landed on main (verification classes + operational verification regex). Could you rebase against main? Conflicts are in `doctor-runtime-checks.ts` and `forensics.ts`. Thanks!

**Comment by drkthng** [comment]
> This PR now has merge conflicts after #2820 and #2898 landed on main (verification classes + operational verification regex). Could you rebase against main? Conflicts are in `doctor-runtime-checks.ts` and `forensics.ts`. Thanks!

Hi Tâches, fixed the conflicts, all checks pass now

**Review by trek-e — APPROVED** [review]
## Adversarial Review: Doctor Hook Compound Key Parsing

### VISION.md Alignment
**Verdict: APPROVE** -- Extracts `splitCompletedKey()` helper to correctly handle `hook/<hookName>/<unitId>` compound keys. Focused bug fix with good test coverage.

### Findings

**1. Root Cause**
The existing code split on `/` and assumed a simple `<type>/<id>` format. Hook keys use `hook/<hookName>/<unitId>`, a three-part compound key. The extracted `splitCompletedKey()` correctly handles both formats.

**2. Shared Helper**
Extracting the helper from `forensics.ts` and sharing it with `doctor-runtime-checks.ts` eliminates the duplicated parsing logic. DRY without over-abstracting.

**3. Test Coverage**
74-line unit test + 36-line integration test. The unit test covers both simple and compound key formats. Integration test verifies the doctor correctly processes hook-completed events.

**4. Prior Reviews**
This PR has reviews from igouss. The feedback appears to have been addressed. No outstanding concerns from those reviews.

### Recommendation
Approve. Clean extraction of a shared helper with thorough test coverage.
