### PR TITLE
fix(gsd): sync milestone DB status in parkMilestone and unparkMilestone

### LINKED ISSUE #2694: bug(park): unparkMilestone desynchronizes DB and filesystem — parked status persists in database
## Problem

Auto-mode failed to start M004 despite the user unparking it with `/gsd unpark M004`. The system proclaimed "All milestones are complete and the discussion didn't produce a new one" even though M004 had an active ROADMAP and was NOT parked on the filesystem.

## Root Cause

**Database-filesystem desynchronization in park/unpark operations**

The `unparkMilestone()` function only removes the `PARKED.md` file but does NOT update the database `milestones.status` field.

**File: `milestone-actions.js:64-72`**
```javascript
export function unparkMilestone(basePath, milestoneId) {
    const mDir = resolveMilestonePath(basePath, milestoneId);
    if (!mDir || !existsSync(mDir))
        return false;
    const parkedPath = join(mDir, buildMilestoneFileName(milestoneId, "PARKED"));
    if (!existsSync(parkedPath))
        return false; // not parked
    unlinkSync(parkedPath);        // ← ONLY removes file
    invalidateAllCaches();         // ← Does NOT update DB
    return true;
}
```

Meanwhile, `deriveStateFromDb()` checks **BOTH** the filesystem marker AND the database status:

**File: `state.js:272-276`**
```javascript
const parkedFile = resolveMilestoneFile(basePath, m.id, "PARKED");
if (parkedFile || m.status === 'parked') {  // ← Checks BOTH
    parkedMilestoneIds.add(m.id);
    continue;  // ← Skips this milestone
}
```

**Result:** After `/gsd unpark M004`:
- Filesystem: `M004-PARKED.md` deleted ✅
- Database: `status='parked'` remains ❌
- State derivation: Skips M004 because `m.status === 'parked'` is still true
- Auto-mode: Sees no active milestone, enters "all complete" terminal state

## Expected Behavior

When a milestone is unparked, **both** the filesystem marker and database status should be synchronized:

1. `unparkMilestone()` should update the database to set `status='active'`
2. `parkMilestone()` should update the database to set `status='parked'`

The missing piece is a DB function in `gsd-db.js`:
```javascript
export function setMilestoneStatus(milestoneId, status) {
    if (!currentDb) throw new GSDError(GSD_STALE_STATE, "gsd-db: No database open");
    currentDb.prepare(`UPDATE milestones SET status = :status WHERE id = :id`)
        .run({ ":id": milestoneId, ":status": status });
}
```

Then in `milestone-actions.js`:
```javascript
export function unparkMilestone(basePath, milestoneId) {
    // ... existing checks ...
    unlinkSync(parkedPath);
    setMilestoneStatus(milestoneId, 'active');  // ← ADD THIS
    invalidateAllCaches();
    return true;
}

export function parkMilestone(basePath, milestoneId, reason) {
    // ... existing checks ...
    writeFileSync(parkedPath, content, "utf-8");
    setMilestoneStatus(milestoneId, 'parked');  // ← ADD THIS
    invalidateAllCaches();
    return true;
}
```

## Environment
- GSD version: 2.51.0
- Model: claude-sonnet-4-5
- Unit: M004 (parked → unparked)

## Reproduction Context
- Phase: pre-planning → terminal (false "all complete")
- Milestone: M004 Google Sheets Two-Way Sync
- State: Database status='parked', filesystem PARKED.md deleted
- User ran `/gsd unpark M004` but auto-mode didn't pick it up

## Forensic Evidence
- **Database query:** `SELECT id, status FROM milestones WHERE id='M004'` → `M004|parked`
- **Filesystem:** `M004-PARKED.md` → file not found (correctly deleted)
- **State derivation:** M004 skipped in `deriveStateFromDb()` lines 272-276 due to `m.status === 'parked'`
- **Doctor issue:** Missing tasks directory for M004/S02 (secondary — M004 never activated so planning couldn't complete)
- **Journal terminal event:** `flow=47936b50` → auto-mode terminated with "All milestones complete" message

## Recovery

To unstick the user right now:

```bash
# Manually fix the database status
sqlite3 .gsd/gsd.db "UPDATE milestones SET status = 'active' WHERE id = 'M004';"

# Then run auto-mode
/gsd auto
```

---
*Auto-generated by `/gsd forensics`*

### PR DESCRIPTION
**Pull request by mastertyko**
## TL;DR

**What:** `parkMilestone` and `unparkMilestone` now update the DB milestone status alongside the filesystem marker.
**Why:** Without this, `deriveStateFromDb` skips unparked milestones because the DB still has `status='parked'`, causing "All milestones complete" even though the milestone was unparked on disk.
**How:** Added `updateMilestoneStatus()` to `gsd-db.ts` and call it from both functions, guarded by `isDbAvailable()`.

## What

- **`gsd-db.ts`**: Added `updateMilestoneStatus(milestoneId, status)` — a simple `UPDATE milestones SET status = :status WHERE id = :id`.
- **`milestone-actions.ts`**: Added `import { isDbAvailable, updateMilestoneStatus }` and called `updateMilestoneStatus` in `parkMilestone` (→ `'parked'`) and `unparkMilestone` (→ `'active'`), both guarded by `isDbAvailable()` with non-fatal `try/catch`.
- **`tests/park-db-sync.test.ts`**: Three regression tests — park updates DB, unpark updates DB, and both work without a DB.

## Why

`deriveStateFromDb` checks **both** the filesystem marker AND the DB status:

```typescript
const parkedFile = resolveMilestoneFile(basePath, m.id, "PARKED");
if (parkedFile || m.status === 'parked') {
    parkedMilestoneIds.add(m.id);
    continue;  // ← skips this milestone
}
```

But `unparkMilestone` only deleted the `PARKED.md` file — it never updated `m.status` in the DB. After `/gsd unpark M004`:
- Filesystem: `M004-PARKED.md` deleted ✅
- Database: `status='parked'` remains ❌
- `deriveStateFromDb`: skips M004 because `m.status === 'parked'`
- Auto-mode: "All milestones complete" — no active milestone found

The same desync existed in `parkMilestone` (file written but DB still says `'active'`), though it was less visible because `deriveStateFromDb` checks the file first.

Closes #2694

## How

**Bug reproduction:**

1. Open an in-memory DB, insert milestone M001 with `status: 'active'`
2. Call `parkMilestone(base, "M001", "deprioritized")` and check `getMilestone("M001").status`
3. Call `unparkMilestone(base, "M001")` and check `getMilestone("M001").status`

Before fix: After park, DB status stays `'active'` (file created but DB not updated). After unpark in a real scenario where DB was manually set to `'parked'`, it would stay `'parked'`.
After fix: After park, DB status is `'parked'`. After unpark, DB status is `'active'`.

## Change type

- [x] `fix` — Bug fix

## Scope

- [x] `gsd extension` — GSD workflow

## Breaking changes

- [x] No breaking changes

## Test plan

- [x] CI passes
- [x] New/updated tests included
- [x] Manual testing — steps described above

**Local CI gate:**
| Step | Result |
|---|---|
| `npm run build` | ✅ pass |
| `npm run typecheck:extensions` | ✅ pass |
| `npm run test:unit` | ✅ 4062 pass, 2 pre-existing fail |
| `npm run test:integration` | ✅ 71 pass, 3 pre-existing fail |

**New tests** (3 in `park-db-sync.test.ts`):
1. `parkMilestone updates DB status to 'parked'` — verifies DB status changes on park
2. `unparkMilestone updates DB status to 'active'` — full park→unpark round-trip
3. `park/unpark are safe when DB is not available` — guard test for filesystem-only projects

## AI disclosure

- [x] This PR includes AI-assisted code — authored with Claude, verified via standalone reproduction script, targeted module tests, and full CI gate.

### CODE REVIEW

File: src/resources/extensions/gsd/milestone-actions.ts [hunk 1]
```diff
@@ -52,6 +53,10 @@ export function parkMilestone(basePath: string, milestoneId: string, reason: str
   ].join("\n");
 
   writeFileSync(parkedPath, content, "utf-8");
+  // Sync DB status so deriveStateFromDb also skips this milestone (#2694)
+  if (isDbAvailable()) {
+    try { updateMilestoneStatus(milestoneId, "parked"); } catch { /* non-fatal */ }
```
Comment (igouss) [inline src/resources/extensions/gsd/milestone-actions.ts]: it's not fatal, but I think either journal entry should be added, or error reported to a user.
I don't think catching and ignoring exceptions is a good pattern.
