### PR TITLE
fix(gsd): include preferences.md in worktree sync and initial seed

### LINKED ISSUE #2684: [Bug]: preferences.md not copied to auto-mode worktree — post_unit_hooks silently disabled
## Summary

`preferences.md` is not seeded into auto-mode worktrees when they are created. Because post-unit hooks (and all other preference-driven config) are defined in `preferences.md`, any hook configured there silently stops firing once auto-mode enters a worktree.

## Root Cause

`copyPlanningArtifacts()` in `src/resources/extensions/gsd/auto-worktree.ts` explicitly lists the files to copy from the source repo's `.gsd/` into the fresh worktree. `preferences.md` is absent from that list:

```typescript
// auto-worktree.ts ~line 630
for (const file of [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "QUEUE.md",
  "STATE.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
]) {
  safeCopy(join(srcGsd, file), join(dstGsd, file), { force: true });
}
// ^^^ preferences.md is missing
```

The same gap exists in `ROOT_STATE_FILES` (~line 50), which drives `syncGsdStateToWorktree()` and `syncWorktreeStateBack()` — so even the ongoing sync passes don't propagate preferences:

```typescript
const ROOT_STATE_FILES = [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
  "QUEUE.md",
  "completed-units.json",
  "metrics.json",
] as const;
// ^^^ preferences.md is missing here too
```

Because `.gsd/` is blanket-gitignored by default, git worktrees are empty fresh checkouts — the worktree bootstrap is the only opportunity to carry config over. Without it, the worktree's `.gsd/` has no `preferences.md` at all.

## Impact

- All `post_unit_hooks` (Telegram, Slack, Discord notifications, custom scripts, etc.) stop firing silently as soon as auto-mode enters a worktree
- `always_use_skills`, `prefer_skills`, `avoid_skills`, and `skill_rules` are ignored inside worktrees
- `custom_instructions` are ignored inside worktrees
- `git.auto_push`, `git.main_branch`, and other git prefs fall back to defaults inside the worktree (the effective preferences loader does load a fallback, but the project-level overrides are lost)
- The bug is silent — no error, no warning, execution continues normally but hooks never fire

## Reproduction

1. Configure a `post_unit_hooks` entry in `.gsd/preferences.md` (e.g. a Telegram notification)
2. Ensure `git.isolation: worktree` is set (the default)
3. Run `/gsd auto`
4. Observe: hooks fire for any milestone that ran before auto-mode created a worktree, then stop completely once the first worktree is entered
5. Confirm: `.gsd/worktrees/<MID>/.gsd/preferences.md` does not exist

## Fix

Add `preferences.md` to both locations:

**1. `copyPlanningArtifacts()`** — the initial seed on worktree creation:

```typescript
for (const file of [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "QUEUE.md",
  "STATE.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
+ "preferences.md",
]) {
  safeCopy(join(srcGsd, file), join(dstGsd, file), { force: true });
}
```

**2. `ROOT_STATE_FILES`** — so ongoing sync passes also propagate it:

```typescript
const ROOT_STATE_FILES = [
  "DECISIONS.md",
  "REQUIREMENTS.md",
  "PROJECT.md",
  "KNOWLEDGE.md",
  "OVERRIDES.md",
  "QUEUE.md",
  "completed-units.json",
  "metrics.json",
+ "preferences.md",
] as const;
```

Note: `preferences.md` should be copied with `force: false` in `syncGsdStateToWorktree()` (additive, project root → worktree) but `force: true` for the initial seed — same pattern as other planning files. The worktree should never override project-root preferences during execution, so the sync-back direction (`syncWorktreeStateBack`) should likely `force: false` for preferences to avoid overwriting changes made via `/gsd prefs` in the main session.

## Environment

- Reproduced on: Windows 11, gsd-gui project, M006/M007 hooks fired (ran before worktree mode), M008 hooks silent (ran inside worktree)
- `git.isolation: worktree` (default)
- Hook type: `post_unit_hooks` with `curl` Telegram notification

### PR DESCRIPTION
**Pull request by mastertyko**
## TL;DR

**What:** Added `preferences.md` to both `ROOT_STATE_FILES` and `copyPlanningArtifacts` file lists in `auto-worktree.ts`.
**Why:** Without this, `post_unit_hooks`, skill rules, custom instructions, and all other preference-driven config silently stop working once auto-mode enters a worktree.
**How:** Two one-line additions to existing file lists, matching the established pattern.

## What

- **`auto-worktree.ts`**: Added `"preferences.md"` to `ROOT_STATE_FILES` (used by `syncGsdStateToWorktree` and `syncWorktreeStateBack`) and to the `copyPlanningArtifacts` file list (initial worktree seed). Added comments explaining why.
- **`tests/preferences-worktree-sync.test.ts`**: Three regression tests — source-audit of both file lists + a functional test that verifies `syncGsdStateToWorktree` actually copies `preferences.md`.

## Why

`.gsd/` is gitignored, so worktrees start with an empty `.gsd/` directory. The worktree bootstrap (`copyPlanningArtifacts`) and ongoing sync (`ROOT_STATE_FILES`) are the only mechanisms to carry config into worktrees.

`preferences.md` was missing from both lists. This caused:
- All `post_unit_hooks` (Telegram, Slack, Discord, custom scripts) to silently stop firing
- `always_use_skills`, `prefer_skills`, `avoid_skills`, and `skill_rules` to be ignored
- `custom_instructions` to be lost
- `git.auto_push`, `git.main_branch`, and other git prefs to fall back to defaults

The bug is completely silent — no error, no warning, hooks just never fire.

Closes #2684

## How

The fix adds `"preferences.md"` to two existing arrays:

```typescript
// ROOT_STATE_FILES — ongoing sync between project root and worktree
const ROOT_STATE_FILES = [
  "DECISIONS.md", "REQUIREMENTS.md", "PROJECT.md", "KNOWLEDGE.md",
  "OVERRIDES.md", "QUEUE.md", "completed-units.json", "metrics.json",
+ "preferences.md",
] as const;

// copyPlanningArtifacts — initial worktree seed
for (const file of [
  "DECISIONS.md", "REQUIREMENTS.md", "PROJECT.md", "QUEUE.md",
  "STATE.md", "KNOWLEDGE.md", "OVERRIDES.md",
+ "preferences.md",
]) { safeCopy(...); }
```

**Bug reproduction:**

1. Create two temp directories simulating a project root and worktree, each with a `.gsd/` directory
2. Write a `preferences.md` with `post_unit_hooks` config in the source `.gsd/`
3. Call `syncGsdStateToWorktree(srcBase, dstBase)` and check if `preferences.md` exists in the destination

Before fix: `preferences.md` is NOT copied — worktree has no preferences, hooks silently disabled
After fix: `preferences.md` IS copied — worktree inherits all preference-driven config

## Change type

- [x] `fix` — Bug fix

## Scope

- [x] `gsd extension` — GSD workflow

## Breaking changes

- [x] No breaking changes

## Test plan

- [x] CI passes
- [x] New/updated tests included
- [x] Manual testing — steps described above

**Local CI gate:**
| Step | Result |
|---|---|
| `npm run build` | ✅ pass |
| `npm run typecheck:extensions` | ✅ pass |
| `npm run test:unit` | ✅ pass (pre-existing failures only) |
| `npm run test:integration` | ✅ 71 pass, 3 pre-existing fail |

**New tests** (3 in `preferences-worktree-sync.test.ts`):
1. `ROOT_STATE_FILES includes preferences.md` — source-audit of the sync list
2. `copyPlanningArtifacts file list includes preferences.md` — source-audit of the seed list
3. `syncGsdStateToWorktree copies preferences.md` — functional test with temp dirs

## AI disclosure

- [x] This PR includes AI-assisted code — authored with Claude, verified via targeted module tests and full CI gate.

### CODE REVIEW

File: src/resources/extensions/gsd/auto-worktree.ts [hunk 1]
```diff
@@ -82,6 +82,8 @@ const ROOT_STATE_FILES = [
   "QUEUE.md",
   "completed-units.json",
   "metrics.json",
+  "preferences.md",  // #2684: without this, post_unit_hooks and all preference-driven
```
Comment (igouss) [inline src/resources/extensions/gsd/auto-worktree.ts]: Should we keep it UPPERCASE for consistency?

Comment (mastertyko) [reply src/resources/extensions/gsd/auto-worktree.ts]: Good eye — I considered this. The file is actually created as lowercase `preferences.md` by the bootstrap code (`gitignore.ts:227`), and `preferences.ts` reads it as lowercase too (lines 90, 98). The uppercase `PREFERENCES.md` is explicitly documented as a legacy mistake:

```ts
// preferences.ts:100
// Bootstrap in gitignore.ts historically created PREFERENCES.md (uppercase) by mistake.
```

So using `preferences.md` here matches the canonical filename that exists on disk. Using `PREFERENCES.md` would silently miss the file on case-sensitive filesystems (Linux).
